name: Lint Checks

on:
  pull_request:

jobs:
  ktlint:
    name: KTLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.2.1/ktlint
          chmod a+x ktlint
          ./ktlint --color
